### ISSUE TITLE
include `-I` doesn't work

### ISSUE THREAD

**Issue by quantjin** [apiaryio/emscripten-docker#12]
Hello, when I add `-I` option to the command, it seems it couldn't find the specified path..., there's always error in the `#include`, saying the header file can't be found

Am I doing it wrong?

e.g. , the header file is in `/home/user/project/include`

`docker run --rm -v $(pwd):/src -t apiaryio/emcc em++ -I"/usr/include" -I"/home/user/project/include" file.cpp -o file.o`

How do I specify `include` path? thanks!

**Comment by w-vi** [comment]
Hi, the `-v $(pwd):/src` is mounting your current directory  to  `/src` in the docker container so the `-I` path have to honor this so if your cwd is  `/home/user/project` then you have to specify the includes as `-I src/include` so that it looks for `/src/include` inside the container. Please ask more if it is not clear.

**Comment by quantjin** [comment]
@w-vi , thanks a lot! now it's working!
